[project]
name = "web-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.5"
dependencies = [
    "flask>=3.1.2",
    "numpy>=2.3.2",
    "requests>=2.32.5",
    "scikit-learn>=1.7.2",
    "waitress>=3.0.2",
]
